### PR TITLE
updated tests and packages to latest

### PR DESCRIPTION
**Pull request by thomascmost**
What Changes
---
- Updated all packages to @latest
- Added `@types/jasmine`
- Replaced `toHaveProperty` with `hasOwnProperty`
- Added a package.lock.json (npm ^5.x.x)
- Removed `mapCoverage` option as that is on by default now

Why
---
Resolves Issue #12

### CODE REVIEW

**Comment by patrickgordon** [comment]
Thanks for the contribution! I'll take a look at this in the coming days as I plan to finish #14 in the coming days.

**Comment by thomascmost** [comment]
@patrickgordon very cool! Thank you. Yeah, this project looks nifty. I'm incorporating it into a new project right now and thought it would be a good time to jump in and help out!

**Comment by thomascmost** [comment]
Can we pull this in?

**Comment by patrickgordon** [comment]
Thanks for your contribution @thomascmost.

**Comment by thomascmost** [comment]
Happy to help! Thank you!

**Pull request merged**
